package com.reed.spanishvocabulary;

/**
 * Created by Reed on 7/27/2016.
 */
public class Chapter1Vocab {
    private VocabWord[] mVocabWords;

    public Chapter1Vocab() {
        mVocabWords = new VocabWord[163];

        mVocabWords[0] = new VocabWord("Buenos días. ¿Cómo estás?","Good morning. How are you?");
        mVocabWords[1] = new VocabWord("Estoy muy bien, gracias. ¿Y tú??","I am fine, thank you. And you?");
        mVocabWords[2] = new VocabWord("¡Hola! ¿Qué tal?","Hi! How is everything?");
        mVocabWords[3] = new VocabWord("Regular, gracias.","The same, thank you.");
        mVocabWords[4] = new VocabWord("Más o menos, gracias.","So, so, thank you.");
        mVocabWords[5] = new VocabWord("Buenas tardes. ¿Cómo está usted?","Good afternoon. How are you?");
        mVocabWords[6] = new VocabWord("Bien, gracias.","Fine, thank you.");
        mVocabWords[7] = new VocabWord("Adiós.","Good bye.");
        mVocabWords[8] = new VocabWord("¡Hasta mañana!","Until tomorrow.");
        mVocabWords[9] = new VocabWord("Buenas noches.","Good evening.");
        mVocabWords[10] = new VocabWord("¡Hasta luego!", "Until later!");
        mVocabWords[11] = new VocabWord("¡Hola! Soy _____ .", "Hello! I am _____ .");
        mVocabWords[12] = new VocabWord("Me llamo _________.", "My name is ______.");
        mVocabWords[13] = new VocabWord("¿Cómo te llamas?", "What is your name?");
        mVocabWords[14] = new VocabWord("Normal","Normal");
        mVocabWords[15] = new VocabWord("Justo","Just");
        mVocabWords[16] = new VocabWord("posible / imposible","Possible / Impossible");
        mVocabWords[17] = new VocabWord("práctico / impráctico","practical / impractical");
        mVocabWords[18] = new VocabWord("probable","probably");
        mVocabWords[19] = new VocabWord("inteligente","intelligent");
        mVocabWords[20] = new VocabWord("terrible","terrible");
        mVocabWords[21] = new VocabWord("maravilloso","marvelous");
        mVocabWords[22] = new VocabWord("espléndido","splendid");
        mVocabWords[23] = new VocabWord("interesante","interesting");
        mVocabWords[24] = new VocabWord("brillante","brilliant");
        mVocabWords[25] = new VocabWord("importante","important");
        mVocabWords[26] = new VocabWord("necesario / innecesario","necessary / unnecessary");
        mVocabWords[27] = new VocabWord("estudioso","studious");
        mVocabWords[28] = new VocabWord("académico","academic");
        mVocabWords[29] = new VocabWord("común","common");
        mVocabWords[30] = new VocabWord("famoso","famous");
        mVocabWords[31] = new VocabWord("impulsivo","impulsive");
        mVocabWords[32] = new VocabWord("cruel","cruel");
        mVocabWords[33] = new VocabWord("sincero","sincere");
        mVocabWords[34] = new VocabWord("generoso","generous");
        mVocabWords[35] = new VocabWord("nervioso","nervous");
        mVocabWords[36] = new VocabWord("religioso","religious");
        mVocabWords[37] = new VocabWord("diplomático","diplomatic");
        mVocabWords[38] = new VocabWord("político","political");
        mVocabWords[39] = new VocabWord("económico", "economical");
        mVocabWords[40] = new VocabWord("Zero","Cero");
        mVocabWords[41] = new VocabWord("One","Uno");
        mVocabWords[42] = new VocabWord("Two","Dos");
        mVocabWords[43] = new VocabWord("Three","Tres");
        mVocabWords[44] = new VocabWord("Four","Cuatro");
        mVocabWords[45] = new VocabWord("Five","Cinco");
        mVocabWords[46] = new VocabWord("Six","Seis");
        mVocabWords[47] = new VocabWord("Seven","Siete");
        mVocabWords[48] = new VocabWord("Eight","Ocho");
        mVocabWords[49] = new VocabWord("Nine","Nueve");
        mVocabWords[50] = new VocabWord("Ten","Diez");
        mVocabWords[51] = new VocabWord("profesor","professor");
        mVocabWords[52] = new VocabWord("estudiante","student");
        mVocabWords[53] = new VocabWord("oficinista","office worker");
        mVocabWords[54] = new VocabWord("secretaria","secretary");
        mVocabWords[55] = new VocabWord("doctor","doctor");
        mVocabWords[56] = new VocabWord("dentista","dentist");
        mVocabWords[57] = new VocabWord("pastor","pastor");
        mVocabWords[58] = new VocabWord("ministro","minister");
        mVocabWords[59] = new VocabWord("músico","musician");
        mVocabWords[60] = new VocabWord("violinista","violinist");
        mVocabWords[61] = new VocabWord("guitarrista","guitarist");
        mVocabWords[62] = new VocabWord("organista","organist");
        mVocabWords[63] = new VocabWord("pianista","pianist");
        mVocabWords[64] = new VocabWord("arquitecto","architect");
        mVocabWords[65] = new VocabWord("ingeniero","engineer");
        mVocabWords[66] = new VocabWord("electricista","electrician");
        mVocabWords[67] = new VocabWord("contratista","contractor");
        mVocabWords[68] = new VocabWord("carpintero","carpenter");
        mVocabWords[69] = new VocabWord("plomero","plumber");
        mVocabWords[70] = new VocabWord("piloto / aviador","pilot / aviator");
        mVocabWords[71] = new VocabWord("general","general");
        mVocabWords[72] = new VocabWord("capitán","captain");
        mVocabWords[73] = new VocabWord("sargento","sergeant");
        mVocabWords[74] = new VocabWord("detective","detective");
        mVocabWords[75] = new VocabWord("policía","police");
        mVocabWords[76] = new VocabWord("la abuela","the grandmother");
        mVocabWords[77] = new VocabWord("el abuelo","the grandfather");
        mVocabWords[78] = new VocabWord("el padre","the father");
        mVocabWords[79] = new VocabWord("la madre","the mother");
        mVocabWords[80] = new VocabWord("la hija","the daughter");
        mVocabWords[81] = new VocabWord("el hijo","the son");
        mVocabWords[82] = new VocabWord("los abuelos","the grandparents");
        mVocabWords[83] = new VocabWord("los padres","the parents");
        mVocabWords[84] = new VocabWord("los hijos","the children");
        mVocabWords[85] = new VocabWord("el hermano","the brother");
        mVocabWords[86] = new VocabWord("la hermana","the sister");
        mVocabWords[87] = new VocabWord("el tío","the uncle");
        mVocabWords[88] = new VocabWord("la tía","the aunt");
        mVocabWords[89] = new VocabWord("el primo","the cousin (boy)");
        mVocabWords[90] = new VocabWord("la prima","the cousin (girl)");
        mVocabWords[91] = new VocabWord("el sobrino","the nephew");
        mVocabWords[92] = new VocabWord("la sobrina","the niece");
        mVocabWords[93] = new VocabWord("el nieto","the grandson");
        mVocabWords[94] = new VocabWord("la nieta","the granddaughter");
        mVocabWords[95] = new VocabWord("los parientes","the relatives");
        mVocabWords[96] = new VocabWord("una puerta","a door");
        mVocabWords[97] = new VocabWord("una ventana","a window");
        mVocabWords[98] = new VocabWord("un libro","a book");
        mVocabWords[99] = new VocabWord("una estudiante","a student (girl)");
        mVocabWords[100] = new VocabWord("un estudiante","a student (boy)");
        mVocabWords[101] = new VocabWord("una profesora","a teacher (woman)");
        mVocabWords[102] = new VocabWord("un profesor","a teacher (man)");
        mVocabWords[103] = new VocabWord("un papel","a paper");
        mVocabWords[104] = new VocabWord("un escritorio / pupitre","a desk / student desk");
        mVocabWords[105] = new VocabWord("un bolígrafo / pluma","a fountain pen / pen");
        mVocabWords[106] = new VocabWord("una silla","a chair");
        mVocabWords[107] = new VocabWord("un cuaderno","a notebook");
        mVocabWords[108] = new VocabWord("un lápiz","a pencil");
        mVocabWords[109] = new VocabWord("una goma","a pencil eraser");
        mVocabWords[110] = new VocabWord("un borrador","a chalkboard eraser");
        mVocabWords[111] = new VocabWord("una pizarra","a chalkboard");
        mVocabWords[112] = new VocabWord("una tiza","a chalk");
        mVocabWords[113] = new VocabWord("Levanten la mano.","Raise your hand.");
        mVocabWords[114] = new VocabWord("Bajen la mano.","Lower your hand.");
        mVocabWords[115] = new VocabWord("Escuchen.","Listen.");
        mVocabWords[116] = new VocabWord("Repitan.","Repeat.");
        mVocabWords[117] = new VocabWord("Párense.","Stand up.");
        mVocabWords[118] = new VocabWord("Siéntense.","Sit down.");
        mVocabWords[119] = new VocabWord("Contesten en español.","Answer in Spanish.");
        mVocabWords[120] = new VocabWord("Abran el libro.","Open the book.");
        mVocabWords[121] = new VocabWord("Cierren el libro.","Close the book.");
        mVocabWords[122] = new VocabWord("¿Hay preguntas?","Are there questions?");
        mVocabWords[123] = new VocabWord("¡Silencio!","Quiet!");
        mVocabWords[124] = new VocabWord("Miren.","Look.");
        mVocabWords[125] = new VocabWord("Por favor.","Please.");
        mVocabWords[126] = new VocabWord("domingo","Sunday");
        mVocabWords[127] = new VocabWord("lunes","Monday");
        mVocabWords[128] = new VocabWord("martes","Tuesday");
        mVocabWords[129] = new VocabWord("miércoles","Wednesday");
        mVocabWords[130] = new VocabWord("jueves","Thursday");
        mVocabWords[130] = new VocabWord("viernes","Friday");
        mVocabWords[130] = new VocabWord("sábado","Saturday");
        mVocabWords[130] = new VocabWord("Hoy es . . .","Today is . . .");
        mVocabWords[130] = new VocabWord("Ayer fue . . .","Yesterday was  . . .");
        mVocabWords[130] = new VocabWord("Mañana será . . .","Tomorrow will be . . .");
        mVocabWords[130] = new VocabWord("una congregación","a congregation");
        mVocabWords[130] = new VocabWord("una iglesia","a church");
        mVocabWords[130] = new VocabWord("un predicador","a preacher");
        mVocabWords[130] = new VocabWord("un coro","a choir");
        mVocabWords[140] = new VocabWord("un himnario","a hymnal");
        mVocabWords[140] = new VocabWord("un(a) cristiano(a)","a Christian");
        mVocabWords[140] = new VocabWord("una Biblia","a Bible");
        mVocabWords[140] = new VocabWord("un creyente","a believer");
        mVocabWords[140] = new VocabWord("un misionero","a missionary");
        mVocabWords[140] = new VocabWord("un Nuevo Testamento","a New Testament");
        mVocabWords[140] = new VocabWord("una oración","a prayer");
        mVocabWords[140] = new VocabWord("un pastor","a pastor / a shepherd");
        mVocabWords[140] = new VocabWord("un himno","a hymn");
        mVocabWords[140] = new VocabWord("una cruz","a cross");
        mVocabWords[150] = new VocabWord("El Señor","Lord");
        mVocabWords[151] = new VocabWord("Jesucristo","Jesus Christ");
        mVocabWords[152] = new VocabWord("Dios","God");
        mVocabWords[153] = new VocabWord("Jehová","Jehovah");
        mVocabWords[154] = new VocabWord("Salmo","Psalms");
        mVocabWords[155] = new VocabWord("Jehová es mi pastor, nada me faltará.  Salmo 23:1","The Lord is my shepherd, I shall not want. Psalms 23:1");
        mVocabWords[156] = new VocabWord("Voy","I am going");
        mVocabWords[157] = new VocabWord("Ven conmigo","Come with me");
        mVocabWords[158] = new VocabWord("El Señor les bendiga","My the Lord bless you");
        mVocabWords[159] = new VocabWord("El va a predicar hoy","He is going to preach today");
        mVocabWords[160] = new VocabWord("Predicador","Preacher");
        mVocabWords[161] = new VocabWord("por invitarme","for inviting me");
        mVocabWords[162] = new VocabWord("por acompañarme","for going with me");
    }

    public VocabWord getVocabWord(int index) {
        return mVocabWords[index];
    }

    public int getLength() {
        return mVocabWords.length;
    }
}
